# Generated by Django 2.1.1 on 2020-02-21 22:50

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=100)),
                ('community_description', models.CharField(max_length=200)),
                ('community_tag', models.CharField(max_length=150)),
                ('community_tag_wiki', models.CharField(max_length=400)),
                ('community_creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('community_builder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type_title', models.CharField(max_length=100)),
                ('post_type_description', models.CharField(max_length=200)),
                ('post_type_tag', models.CharField(max_length=150)),
                ('post_type_creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('formfield', django.contrib.postgres.fields.jsonb.JSONField(default='')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Community')),
                ('post_type_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
