# Generated by Django 2.1.1 on 2020-02-23 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20200222_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/community'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='community_modification_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 23, 12, 38, 31, 709686, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='community',
            name='community_creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 23, 12, 38, 35, 720715, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='community',
            name='community_slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
