# Generated by Django 2.1.1 on 2020-03-30 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_community_community_modifiedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community_image',
            field=models.ImageField(upload_to='community'),
        ),
        migrations.AlterField(
            model_name='post_type',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community', to='firstapp.Community'),
        ),
    ]
