# Generated by Django 2.1.1 on 2020-04-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20200330_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_type',
            name='community',
        ),
        migrations.RemoveField(
            model_name='post_type',
            name='post_type_owner',
        ),
        migrations.DeleteModel(
            name='Post_Type',
        ),
    ]
