# Generated by Django 2.1.1 on 2020-04-19 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0008_auto_20200418_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100)),
                ('post_description', models.CharField(max_length=200)),
                ('post_tag', models.CharField(max_length=150)),
                ('post_creation_date', models.DateTimeField(blank=True, editable=False)),
                ('post_modification_date', models.DateTimeField(blank=True, editable=False)),
                ('post_slug', models.SlugField(editable=False, max_length=150, unique=True)),
                ('post_image', models.ImageField(upload_to='post')),
                ('post_builder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('post_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
