# Generated by Django 2.1.1 on 2020-04-19 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='community_tag_wiki',
        ),
    ]
